<programa> ::= <tipo_juego> <grid> <configuraciones_opcionales> <definiciones> <personalizaciones> <eventos>

<tipo_juego> ::= "GAME_TYPE" "TETRIS"
<grid>       ::= "GAME_GRID" "(" <numero> "," <numero> ")"

<configuraciones_opcionales> ::= <game_color> | e
<game_color>                 ::= "GAME_COLOR" <identificador>

<definiciones> ::= <definicion_shape> | <definicion_shape> <definiciones>

<definicion_shape> ::= "DEFINE" "SHAPE" <identificador> ":" <estados> "END"
<estados>          ::= <estado> | <estado> <estados>
<estado>           ::= "STATE" <numero> ":" <matriz>
<matriz>           ::= <fila> | <fila> <matriz>
<fila>             ::= "[" <valores_fila> "]"
<valores_fila>     ::= <numero> | <numero> "," <valores_fila>

<personalizaciones> ::= <regla_personalizacion> <personalizaciones> | e
<regla_personalizacion> ::= <definicion_color> | <definicion_chance> | <definicion_powerup>

<definicion_color>   ::= "COLOR" <identificador> ":" <hex_color>
<definicion_chance>  ::= "CHANCE" <identificador> ":" <numero>
<definicion_powerup> ::= "POWERUP" <identificador> ":" <numero>

<hex_color>     ::= <hex_digit> <hex_digit> <hex_digit> <hex_digit> <hex_digit> <hex_digit>
<hex_digit>     ::= "0"..."9" | "A"..."F"

<eventos>       ::= <evento> | <evento> <eventos>
<evento>        ::= "ON" <nombre_evento_tetris> ":" <acciones_tetris> "END"
<nombre_evento_tetris> ::= "START" | "TICK" | "LINE_CLEAR" | "KEY_UP" | "KEY_DOWN" | "KEY_LEFT" | "KEY_RIGHT"
<acciones_tetris>      ::= <accion_tetris> | <accion_tetris> <acciones_tetris>

<accion_tetris> ::= <accion_spawn> | <accion_mover> | <accion_rotar> | <accion_puntos> | <accion_game_over>
<accion_spawn>  ::= "SPAWN" "RANDOM_SHAPE"
<accion_mover>  ::= "MOVE" "CURRENT_PIECE" <direccion>
<accion_rotar>  ::= "ROTATE" "CURRENT_PIECE"
<accion_puntos> ::= "INCREASE_SCORE" <numero>
<accion_game_over> ::= "GAME_OVER"

<direccion>     ::= "LEFT" | "RIGHT" | "DOWN"
<identificador> ::= <letra> | <letra> <identificador>
<numero>        ::= <digito> | <digito> <numero>
<letra>         ::= "A"..."Z" | "_"
<digito>        ::= "0"..."9"